### ISSUE TITLE
Architecture 

### ISSUE THREAD

**Issue by adamhathcock** [abauzac/realworld-netcore-kit#9]
Looking briefly, I think the overall structure is a bit heavy handed and old hat to be a nice display of what modern asp.net core  can be like.

I think it should aim for something more like this: https://github.com/jbogard/ContosoUniversityCore/

Some reading: https://lostechies.com/jimmybogard/2015/05/05/cqrs-with-mediatr-and-automapper/
https://codeopinion.com/thin-controllers-cqrs-mediatr/

I'm willing to contribute a lot to this and I can do some first bits to show more.  I'm no fan of EF but I tend to avoid Mongo.  However, if Mongo is what all the other projects are doing then good.  Sticking with the hip tools for this showcase is probably good.

I'm using asp.net Core in docker on AWS in production right now so this is alll familiar to me.

Might start with a nice Cake script :)

**Comment by abauzac** [comment]
Hi @adamhathcock 
Thanks for contributing, I've never used the CQRS pattern but I quite get your point. However, even though there are some advantages with this architecture and could really fit for a huge project with complex domain, I think we should stick to a simple architecture (even if it looks "old hat" :)  ) 

The "realworld" project is not here to show "how far" you can go with this technology, but more "how you can start" with it. I suggest you to look at the _already validated_ repos here : https://github.com/gothinkster/realworld and I think you'll get what I mean. 

There might be one way to get a little closer to the CQRS pattern : we should use the repository classes directly into the controller for GET requests. In this cases, the BLL layer is quite useless and the controller will still be thin enough. 

I've fav'ed the ContosoUniversityCore to better understand CQRS , thanks for the share!

Hope to see your contribution anyway ! :)

**Comment by adamhathcock** [comment]
I don't think I'll be helping at this time.  The direction you're going in and the chosen architecture patterns tell me that you're not really open to picking standards from the community or Microsoft.

I may fork this myself and submit to show how easy and tiny an ASP.NET Core project can be.

Good luck to you and this project.
